"""Load initial companies data

Revision ID: 30c106c2abd2
Revises: e4ffd19ab819
Create Date: 2025-07-20 15:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from app.models.company import Company
from app.database import get_db

# revision identifiers, used by Alembic.
revision = "30c106c2abd2"
down_revision = "e4ffd19ab819"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    db = next(get_db())
    companies = [
        Company(
            name="Tech Innovate",
            industry="Technology",
            location="San Francisco, CA, USA",
            latitude=37.7749,
            longitude=-122.4194,
            geom="SRID=4326;POINT(-122.4194 37.7749)",
        ),
        Company(
            name="Maple Enterprises",
            industry="Manufacturing",
            location="Toronto, ON, Canada",
            latitude=43.6532,
            longitude=-79.3832,
            geom="SRID=4326;POINT(-79.3832 43.6532)",
        ),
        Company(
            name="London Analytics",
            industry="Finance",
            location="London, UK",
            latitude=51.5074,
            longitude=-0.1278,
            geom="SRID=4326;POINT(-0.1278 51.5074)",
        ),
        Company(
            name="Sydney Solutions",
            industry="Consulting",
            location="Sydney, NSW, Australia",
            latitude=-33.8688,
            longitude=151.2093,
            geom="SRID=4326;POINT(151.2093 -33.8688)",
        ),
        Company(
            name="Eco Ventures",
            industry="Renewable Energy",
            location="Berlin, Germany",
            latitude=52.5200,
            longitude=13.4050,
            geom="SRID=4326;POINT(13.4050 52.5200)",
        ),
        Company(
            name="Nippon Tech",
            industry="Technology",
            location="Tokyo, Japan",
            latitude=35.6762,
            longitude=139.6503,
            geom="SRID=4326;POINT(139.6503 35.6762)",
        ),
        Company(
            name="Sao Paulo Systems",
            industry="Software",
            location="Sao Paulo, Brazil",
            latitude=-23.5505,
            longitude=-46.6333,
            geom="SRID=4326;POINT(-46.6333 -23.5505)",
        ),
        Company(
            name="Mumbai Motors",
            industry="Automotive",
            location="Mumbai, India",
            latitude=19.0760,
            longitude=72.8777,
            geom="SRID=4326;POINT(72.8777 19.0760)",
        ),
        Company(
            name="Paris Designs",
            industry="Fashion",
            location="Paris, France",
            latitude=48.8566,
            longitude=2.3522,
            geom="SRID=4326;POINT(2.3522 48.8566)",
        ),
        Company(
            name="Cape Town Creations",
            industry="Creative Arts",
            location="Cape Town, South Africa",
            latitude=-33.9249,
            longitude=18.4241,
            geom="SRID=4326;POINT(18.4241 -33.9249)",
        ),
        Company(
            name="Beijing Biotech",
            industry="Biotechnology",
            location="Beijing, China",
            latitude=39.9042,
            longitude=116.4074,
            geom="SRID=4326;POINT(116.4074 39.9042)",
        ),
        Company(
            name="Moscow Manufacturing",
            industry="Manufacturing",
            location="Moscow, Russia",
            latitude=55.7558,
            longitude=37.6173,
            geom="SRID=4326;POINT(37.6173 55.7558)",
        ),
        Company(
            name="Dubai Dynamics",
            industry="Real Estate",
            location="Dubai, UAE",
            latitude=25.2048,
            longitude=55.2708,
            geom="SRID=4326;POINT(55.2708 25.2048)",
        ),
        Company(
            name="Singapore Solutions",
            industry="Consulting",
            location="Singapore",
            latitude=1.3521,
            longitude=103.8198,
            geom="SRID=4326;POINT(103.8198 1.3521)",
        ),
        Company(
            name="Stockholm Systems",
            industry="Technology",
            location="Stockholm, Sweden",
            latitude=59.3293,
            longitude=18.0686,
            geom="SRID=4326;POINT(18.0686 59.3293)",
        ),
        Company(
            name="Mexico City Motors",
            industry="Automotive",
            location="Mexico City, Mexico",
            latitude=19.4326,
            longitude=-99.1332,
            geom="SRID=4326;POINT(-99.1332 19.4326)",
        ),
        Company(
            name="Bangkok Biotech",
            industry="Biotechnology",
            location="Bangkok, Thailand",
            latitude=13.7563,
            longitude=100.5018,
            geom="SRID=4326;POINT(100.5018 13.7563)",
        ),
        Company(
            name="Amsterdam Analytics",
            industry="Finance",
            location="Amsterdam, Netherlands",
            latitude=52.3676,
            longitude=4.9041,
            geom="SRID=4326;POINT(4.9041 52.3676)",
        ),
        Company(
            name="Seoul Software",
            industry="Software",
            location="Seoul, South Korea",
            latitude=37.5665,
            longitude=126.9780,
            geom="SRID=4326;POINT(126.9780 37.5665)",
        ),
        Company(
            name="Nairobi Innovations",
            industry="Technology",
            location="Nairobi, Kenya",
            latitude=-1.2921,
            longitude=36.8219,
            geom="SRID=4326;POINT(36.8219 -1.2921)",
        ),
    ]
    db.add_all(companies)
    db.commit()
    # Reset the id sequence to avoid conflicts
    op.execute(
        """
        SELECT setval(pg_get_serial_sequence('companies', 'id'), 
                      (SELECT COALESCE(MAX(id), 0) FROM companies));
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE companies RESTART IDENTITY;")
    # ### end Alembic commands ###
